In [1]:
import numpy as np

In [2]:
c = np.arange (1, 25).reshape ((2, 3, 4))

In [3]:
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [4]:
c.shape

(2, 3, 4)

In [5]:
c.ndim

3

In [6]:
c [1, 2, :]

array([21, 22, 23, 24])

In [7]:
c.ndim

3

In [8]:
c [1, 2, :].ndim

1

In [9]:
c [1, :, :].ndim

2

In [10]:
b = np.array ([[1, 0, 0], [2, 1, 2], [2, np.nan, 1]])

In [11]:
b

array([[ 1.,  0.,  0.],
       [ 2.,  1.,  2.],
       [ 2., nan,  1.]])

In [12]:
type (b)

numpy.ndarray

In [13]:
b [1, 2]

np.float64(2.0)

In [14]:
b [1, 2] = 4

In [15]:
b

array([[ 1.,  0.,  0.],
       [ 2.,  1.,  4.],
       [ 2., nan,  1.]])

In [16]:
b[2, : ] = 6
# This is equivalent to b[2, ] = 6 bcz the the trailing comma , is optional when selecting a row.

In [17]:
b

array([[1., 0., 0.],
       [2., 1., 4.],
       [6., 6., 6.]])

In [18]:
b [: , 2] = 9

In [19]:
b

array([[1., 0., 9.],
       [2., 1., 9.],
       [6., 6., 9.]])

In [20]:
b > 5

array([[False, False,  True],
       [False, False,  True],
       [ True,  True,  True]])

In [21]:
100 * (b > 5)

array([[  0,   0, 100],
       [  0,   0, 100],
       [100, 100, 100]])

In [23]:
a = np.array ([3, 8, -2, 43, 12, 1, 8])

In [24]:
a

array([ 3,  8, -2, 43, 12,  1,  8])

In [26]:
a.shape

(7,)

In [27]:
a.ndim

1

In [28]:
a.reshape ([7,1])

array([[ 3],
       [ 8],
       [-2],
       [43],
       [12],
       [ 1],
       [ 8]])

In [29]:
help (np.diff)

Help on _ArrayFunctionDispatcher in module numpy:

diff(a, n=1, axis=-1, prepend=<no value>, append=<no value>)
    Calculate the n-th discrete difference along the given axis.
    
    The first difference is given by ``out[i] = a[i+1] - a[i]`` along
    the given axis, higher differences are calculated by using `diff`
    recursively.
    
    Parameters
    ----------
    a : array_like
        Input array
    n : int, optional
        The number of times values are differenced. If zero, the input
        is returned as-is.
    axis : int, optional
        The axis along which the difference is taken, default is the
        last axis.
    prepend, append : array_like, optional
        Values to prepend or append to `a` along axis prior to
        performing the difference.  Scalar values are expanded to
        arrays with length 1 in the direction of axis and the shape
        of the input array in along all other axes.  Otherwise the
        dimension and shape must match `a` exce

In [30]:
d = np.array([2,5,8,9])

In [31]:
d

array([2, 5, 8, 9])

In [35]:
np.all (np.diff(d)) > 0

np.True_

In [37]:
# np.all (np.diff (np.array([21,8,9]))) > 0

np.True_

In [38]:
np.all (np.diff (np.array([21,8,9])) > 0)

np.False_